### PR TITLE
tweaks for RF3

### PR DESCRIPTION
**Pull request by gferreira**

### CODE REVIEW

**Comment by typemytype** [comment]
a other tweak that must be done is using ufoLib from fontTools

**Comment by colinmford** [comment]
@asaumierdemers Can we merge this with the master branch, or move the Mechanic link to the RoboDocs repo?

**Comment by asaumierdemers** [comment]
Sorry for the delay, I didn't get the notification until now

**Comment by typemytype** [comment]
thanks!!

**Pull request merged**
